import {
  ActivityCategory,
  ActivityLevel,
  ActivityNature,
  StudentType,
} from '@prisma/client';

export type CatalogActivity = {
  slug: string;
  title: string;
  description: string;
  category: ActivityCategory;
  nature: ActivityNature;
  level: ActivityLevel;
  hours: number;
  eligibleYears: number[];
  studentProgram: StudentType | null;
  leaderOnly?: boolean;
};

/** รายการกิจกรรมตามประกาศ/คู่มือ ม.ราชภัฏสุรินทร์ (ปรับให้สอดคล้องงานวิจัย) */
export const SRRU_ACTIVITY_CATALOG: CatalogActivity[] = [
  // —— ภาคปกติ: บังคับแกน ชั้นปีที่ 1 (ข้อ 8.1.1) — 6 ชม./กิจกรรม ——
  {
    slug: 'orient-uni-y1',
    title: 'ปฐมนิเทศนักศึกษา ระดับมหาวิทยาลัย',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับแกน สำหรับนักศึกษาชั้นปีที่ 1 ภาคปกติ',
    category: ActivityCategory.ACADEMIC,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1],
    studentProgram: StudentType.REGULAR,
  },
  {
    slug: 'orient-fac-y1',
    title: 'ปฐมนิเทศนักศึกษา ระดับคณะ',
    description: 'กิจกรรมคณะแบบบังคับแกน สำหรับนักศึกษาชั้นปีที่ 1 ภาคปกติ',
    category: ActivityCategory.ACADEMIC,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.FACULTY,
    hours: 6,
    eligibleYears: [1],
    studentProgram: StudentType.REGULAR,
  },
  {
    slug: 'waikru-uni-y1',
    title: 'ไหว้ครู ระดับมหาวิทยาลัย',
    description: 'พิธีไหว้ครูสำหรับนักศึกษาใหม่ ชั้นปีที่ 1',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1],
    studentProgram: StudentType.REGULAR,
  },
  {
    slug: 'waikru-fac-y1',
    title: 'ไหว้ครู ระดับคณะ',
    description: 'พิธีไหว้ครูระดับคณะ สำหรับนักศึกษาใหม่ ชั้นปีที่ 1',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.FACULTY,
    hours: 6,
    eligibleYears: [1],
    studentProgram: StudentType.REGULAR,
  },
  {
    slug: 'royal-seal',
    title: 'พิธีอัญเชิญตราพระราชลัญจกร',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับแกน',
    category: ActivityCategory.CULTURE,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: StudentType.REGULAR,
  },
  {
    slug: 'intl-culture-show',
    title: 'การแสดงศิลปวัฒนธรรมนานาชาติ',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับแกน',
    category: ActivityCategory.CULTURE,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1, 2, 3],
    studentProgram: StudentType.REGULAR,
  },
  // —— ภาคปกติ ชั้นปีที่ 2–3 (ข้อ 8.1.2–8.1.3) ——
  {
    slug: 'waikru-uni-leader-y23',
    title: 'ไหว้ครู ระดับมหาวิทยาลัย (ผู้นำชั้นเรียน/ตัวแทน)',
    description: 'สำหรับผู้นำชั้นเรียนหรือตัวแทนนักศึกษา ชั้นปีที่ 2–3',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [2, 3],
    studentProgram: StudentType.REGULAR,
    leaderOnly: true,
  },
  {
    slug: 'waikru-fac-leader-y23',
    title: 'ไหว้ครู ระดับคณะ (ผู้นำชั้นเรียน/ตัวแทน)',
    description: 'สำหรับผู้นำชั้นเรียนหรือตัวแทนนักศึกษา ชั้นปีที่ 2–3',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.FACULTY,
    hours: 6,
    eligibleYears: [2, 3],
    studentProgram: StudentType.REGULAR,
    leaderOnly: true,
  },
  // —— ภาคปกติ ชั้นปีที่ 4 (ข้อ 8.1.4) ——
  {
    slug: 'commencement-y4',
    title: 'ปัจฉิมนิเทศ (ปฐมนิเทศบัณฑิต)',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับแกน สำหรับชั้นปีที่ 4',
    category: ActivityCategory.ACADEMIC,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [4],
    studentProgram: StudentType.REGULAR,
  },
  // —— ภาคพิเศษ บังคับแกน (ข้อ 8.2) ——
  {
    slug: 'sp-orient-uni',
    title: 'ปฐมนิเทศนักศึกษา ภาคพิเศษ (มหาวิทยาลัย)',
    description: 'กิจกรรมบังคับแกนสำหรับนักศึกษาภาคพิเศษ',
    category: ActivityCategory.ACADEMIC,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1],
    studentProgram: StudentType.SPECIAL,
  },
  {
    slug: 'sp-waikru',
    title: 'ไหว้ครู นักศึกษาใหม่ ภาคพิเศษ',
    description: 'กิจกรรมบังคับแกนภาคพิเศษ',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1],
    studentProgram: StudentType.SPECIAL,
  },
  {
    slug: 'sp-sports-inter',
    title: 'กีฬาระหว่างคณะ (ภาคพิเศษ)',
    description: 'กิจกรรมบังคับแกนภาคพิเศษ',
    category: ActivityCategory.SPORTS,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [1, 2, 3],
    studentProgram: StudentType.SPECIAL,
  },
  {
    slug: 'sp-commencement',
    title: 'ปัจฉิมนิเทศ ภาคพิเศษ',
    description: 'กิจกรรมบังคับแกนสำหรับบัณฑิตภาคพิเศษ',
    category: ActivityCategory.ACADEMIC,
    nature: ActivityNature.CORE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 6,
    eligibleYears: [4],
    studentProgram: StudentType.SPECIAL,
  },
  // —— บังคับเลือก มหาวิทยาลัย (ข้อ 8.3) — 5 ชม./กิจกรรม ——
  {
    slug: 'star-moon',
    title: 'ประกวดดาว–เดือน',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.CULTURE,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'candle-lent',
    title: 'ประเพณีแห่เทียนเข้าพรรษา',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.CULTURE,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'sports-intra',
    title: 'กีฬาภายในคณะ',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.SPORTS,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.FACULTY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'sports-inter',
    title: 'กีฬาระหว่างคณะ',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.SPORTS,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'loy-krathong',
    title: 'วันลอยกระทง',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.CULTURE,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'children-day',
    title: 'วันเด็กแห่งชาติ',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.VOLUNTEERING,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'student-election',
    title: 'เลือกตั้งองค์กรนักศึกษา',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'national-religious-days',
    title: 'วันสำคัญทางศาสนาและชาติ',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'volunteer',
    title: 'กิจกรรมจิตอาสา',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.VOLUNTEERING,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'club',
    title: 'กิจกรรมชมรม',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือก',
    category: ActivityCategory.CULTURE,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'faculty-organized',
    title: 'กิจกรรมที่คณะ/ภาควิชาจัด',
    description: 'กิจกรรมมหาวิทยาลัยแบบบังคับเลือกตามที่คณะกำหนด',
    category: ActivityCategory.ACADEMIC,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.FACULTY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'external-approved',
    title: 'กิจกรรมหน่วยงานภายนอก (อนุมัติแล้ว)',
    description: 'กิจกรรมภายนอกที่มหาวิทยาลัยรับรองตามข้อ 10',
    category: ActivityCategory.VOLUNTEERING,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
  },
  {
    slug: 'makeup',
    title: 'กิจกรรมซ่อมเสริม (ตามที่กองพัฒนานักศึกษากำหนด)',
    description: 'สำหรับนักศึกษาที่ยังไม่ครบชั่วโมงตามข้อ 17',
    category: ActivityCategory.ETHICS,
    nature: ActivityNature.ELECTIVE_REQUIRED,
    level: ActivityLevel.UNIVERSITY,
    hours: 5,
    eligibleYears: [1, 2, 3, 4],
    studentProgram: null,
    leaderOnly: false,
  },
];
